export TOKENIZERS_PARALLELISM=false
export MODEL_NAME="/workspace/StableAvatar/checkpoints/Wan2.1-Fun-V1.1-1.3B-InP"

CUDA_VISIBLE_DEVICES=0 python inference.py \
  --config_path="deepspeed_config/wan2.1/wan_civitai.yaml" \
  --pretrained_model_name_or_path=$MODEL_NAME \
  --transformer_path="/workspace/StableAvatar/checkpoints/StableAvatar-1.3B/transformer3d-square.pt" \
  --pretrained_wav2vec_path="/workspace/StableAvatar/checkpoints/wav2vec2-base-960h" \
  --validation_reference_path="/workspace/StableAvatar/examples/case-8/reference.png" \
  --validation_driven_audio_path="/workspace/StableAvatar/examples/case-8/sub_clip.mp3" \
  --output_dir="/workspace/StableAvatar/output_infer" \
  --validation_prompts="A middle-aged man with glasses and dark hair wearing a dark polo shirt, speaking naturally with gentle head movements, professional indoor setting with soft lighting." \
  --seed=42 \
  --ulysses_degree=1 \
  --ring_degree=1 \
  --motion_frame=25 \
  --sample_steps=50 \
  --width=512 \
  --height=512 \
  --overlap_window_length=5 \
  --clip_sample_n_frames=81 \
  --GPU_memory_mode="model_full_load" \
  --sample_text_guide_scale=3.0 \
  --sample_audio_guide_scale=5.0
